services: 
  backend:
    build: ./backend
    container_name: ballxpit-backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    # volumes:
    #   - sqlite_data:/app/prisma/data
    networks:
      - default
      - media_net

  frontend:
    build: ./frontend
    container_name: ballxpit-frontend
    environment:
      - API_URL=http://ballxpit-backend:3000
      - VITE_API_URL=http://api.ballxpitwiki.com
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - default
      - media_net

volumes:
  sqlite_data:

networks:
  media_net:
    external: true
    name: home-server_media_net
